### PR TITLE
Code Quality: Simplify directories

### PR DESCRIPTION
**Pull request by Lamparter**
Related: #293 (hey there!)
_This pull request was authored on behalf of @RiversideValley_

### Before the change?

* **Structure:** solution default

### After the change?

* **Structure:** simplified directories

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added: #322 

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

_No_

---

Hello (for the third time) 😁
In this PR, I (on behalf of @0x5bfa) have simplified the root directory/subdirectories to match common practices on GitHub. Took a while to get the configuration right, but everything builds correctly and packages are references as they should be. :octocat:

### CODE REVIEW

**Review by nickfloyd — CHANGES_REQUESTED** [review]
These are great changes @Lamparter.  A couple of things to get this all wrapped up...

* You'l'l need to modify the workflow for the generator to make sure the models go in the `src/` folder now > `./Octokit.GraphQL/` to `./src/Octokit.GraphQL/`
* This might also be a good time to move to .NET 8 / at least move the generator from `netcoreapp3.1` to `net8.0`
* As a factor of clean up we can delete `.travis.yaml`,`appveyor.yaml`, and the `*.ncrunchsolution` files 
* Given that this is already a "large" PR due to the move you might consider running the generator and checking in the results `dotnet run --project ./Tools/Generate/Generate.csproj -- $GH_TOKEN ./Octokit.GraphQL/` to update all of the models
* The `dotnetcore.yml` workflow should be updated as well to reflect the new structure
* The `integration-tests.yml` workflow should be updated as well to reflect the new structure
* The nuspec file `Octokit.GraphQL.nuspec` should be updated to reflect the new structure

**Comment by Lamparter** [comment]
Thanks for the review! Most of these change I've implemented (readme, src dir, net8.0) were suggested by the kind @0x5bfa so thank him for having lots of ideas for this project! ❤️
I've mainly focused on .NET 8 in #321 so unless you want me to bring those changes here I'll keep these PRs separate 😅
I'll make sure to implement what you've requested and I'll run the source generator as well. 😁

**Comment by nickfloyd** [comment]
>  I've mainly focused on .NET 8 in #321 so unless you want me to bring those changes here I'll keep these PRs separate 😅 

Keep it there, I think that's the right move unless you run into anything that would prevent you from keeping them separate.

> I'll make sure to implement what you've requested and I'll run the source generator as well. 😁
Sounds good!  I'm looking forward to getting these changes in!

**Comment by 0x5bfa** [comment]
> A couple of things to get this all wrapped up...

Thank you for the review. If this is hard to review, we have a preparation for separating the changes into a few PRs, merge into another branch on this repo and then merge the branch into main.

We'll update workflows as well. As a side note, what else we have in our mind is to configure a workflow to run the generator daily or weekly to update the GraphQL models, by doing so we'll be able to include those changes in the next releases without running it manually which surely is troublesome.

**Comment by 0x5bfa** [comment]
> A couple of things to get this all wrapped up...

Thank you for the review. If this is hard to review, we have a preparation for separating the changes into a few PRs, merging into another branch on this repo and then merging that branch into the main.

We'll make sure to update workflows as well. As a side note, what else we have in our mind is to configure a workflow to run the model generator daily or weekly to update the GraphQL models, by doing so we'll be able to include those changes in the next releases without running it manually which is surely a troublesome work.

**Comment by Lamparter** [comment]
@0x5bfa Where do you want to bring these changes?

**Comment by 0x5bfa** [comment]
To the upcoming PR.

**Comment by 0x5bfa** [comment]
I fixed the CI.
Probably it also should the following but I'd hold off for now
- Use .NET 8
- Rename to ci.yml or something not to include "netcore"

**Comment by Lamparter** [comment]
https://github.com/octokit/octokit.graphql.net/actions/runs/10925402467/job/30326798453?pr=325#step:9:15
There are lots of NuGet warnings here, should fix (in another PR)

**Comment by nickfloyd** [comment]
Hey @Lamparter & @0x5bfa thanks for the changes here ❤️.  Everything looks good.  Once you get the merge conflict resolved I'll get this merged in.  Also, re: https://github.com/octokit/octokit.graphql.net/pull/321 - once you move that one out of draft I'll take a look at it.  

Again, thank you both for making this and our community better!

**Review by nickfloyd — APPROVED** [review]

**Comment by 0x5bfa** [comment]
Some CI is failing, let's fix shortly.

**Comment by Lamparter** [comment]
Oh crap I forgot to update the codebase structure in the README

**Pull request merged**
