### PR TITLE
Fix GraphQL entity names in subqueries

### LINKED ISSUE #298: [BUG]: Sub-queries in GraphQL use C# type names not GraphQL entity names
### What happened?

When creating a query which generates subqueries, e.g. 

```
new Query()
                .RepositoryOwner("foo")
                .Repositories()
                .AllPages(100)
                .Select(x => x.Name)
```

The generated GraphQL for subqueries uses the C# type name for, e.g. the `RepositoryOwner` entity type:

```
query($__id: ID!, $__after: String) {
  node(id: $__id) {
    __typename
    ... on StubIRepositoryOwner {
      repositories(first: 100, after: $__after) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          name
        }
      }
    }
  }
}
```

(See the `StubIRepositoryOwner` isntead of the expected `RepositoryOwner`)

### Versions

Running from HEAD

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jMarkP**
Resolves #298

----

### Before the change?

* Described in #298. When generating the GraphQL for subqueries, the query builder uses the C# type name, not the GraphQL entity type

### After the change?

* The model generator now emits the `[GraphQLIdentifier(...)]` attribute on all generated interfaces and stubs, and this gets read by `GetIdentifier` when generating the GraphQL syntax. 

### Other information

* I also regenerated the model from the schema. The first commit on this PR is just that straight-up regeneration. The other commits fix the issue.

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
@jMarkP do you have thoughts about the testing errors we're seeing here?

**Comment by jMarkP** [comment]
@kfcampbell thanks for kicking that off. Ah looks like I must have missed that class of tests when I ran locally. Will add a fix next time I have a chance.

**Comment by jMarkP** [comment]
@kfcampbell - have managed to fix the unit tests - turned out to be a simple fix!

**Review by kfcampbell — APPROVED** [review]
Thank you @jMarkP! We appreciate the contributions.

**Comment by jMarkP** [comment]
> Thank you @jMarkP! We appreciate the contributions.

You're welcome! Thanks for the merge

**Pull request merged**
