### PR TITLE
Schema update

### PR DESCRIPTION
**Pull request by jcansdale**
Attempt to update the schema. Unfortunately the updated scheme didn't compile. 😢 

Hey @grokys or @StanleyGoldman 👋 Any idea why https://github.com/octokit/octokit.graphql.net/pull/211/commits/6b33125e13720811a2cfb8afdf3ecebc41f83b8e was necessary?

I wonder if https://github.com/octokit/octokit.graphql.net/pull/211/commits/7054cd14913b1c935bc5edc4e046795851dbf3a0 is what it's supposed to be? 🤔

### CODE REVIEW

**Comment by brphelps** [comment]
It's worth mentioning that without this PR the client fails due to the newly added ecosystem "Composer"

**Comment by brphelps** [comment]
@grokys or @StanleyGoldman any chance this could get reviewed? It seems like a no op and unblocks usage of the lib :).

**Comment by jcansdale** [comment]
> It's worth mentioning that without this PR the client fails due to the newly added ecosystem "Composer" for the securityVulnerabilities API

Could you give more details about this? It's it the schema update that fixes it?

**Comment by brphelps** [comment]
Yeah -- It's an enum value for data that comes back from the API.

**Comment by jcansdale** [comment]
@brphelps I think you should be able to review this PR now. 🤞

**Comment by brphelps** [comment]
It looks like the generator thinks that audit's Actor is a Union instead of an Interface -- it seems like all the other Actor props are Interfaces, which leads to "as expected" generation. Is there a chance this is an issue on some sort of service level metadata?

**Pull request merged**
