### PR TITLE
Addressed Issue #243 

### PR DESCRIPTION
**Pull request by MichaelDenwood**
#243 
Added  a new overload of CreateMethodCall that accepts Expression<Func<TObject, IEnumerable<TValue>>> selector, means that 
Implemented ToList Method here : octokit.graphql.net/Octokit.GraphQL.Core/QueryableListExtensions.cs

### CODE REVIEW

**Comment by jcansdale** [comment]
Hi @MichaelDenwood 👋 

Thanks for working on this!

I was wondering if we could separate the fix from the schema update? Ideally I'd like to create a workflow that automatically updates the schema.

**Review by MichaelDenwood — COMMENTED** [review]
Updated as requested

**Review by jcansdale — CHANGES_REQUESTED** [review]
Thanks for the update!

Do you think it makes sense to uncomment this line as part of the PR?
https://github.com/MichaelDenwood/octokit.graphql.net/blob/master/Octokit.GraphQL/Model/User.cs#L221

**Comment by MichaelDenwood** [comment]
I can do that but it will take me some time.  I am on several large projects at the moment.  On a side note, I am using this product to connect to both GitHub and GitHub Enterprise.  In order to make this work, I had to add a field to the user class, suspendedDate, to support my needs for GitHub Enterprise.  I did this in my own fork that I am not merging back.  I wanted to bring this to you attention if you didn't already know that there are schema differences between the GitHub cloud offering and the on premises appliance.

**Comment by jcansdale** [comment]
> I can do that but it will take me some time.

Thanks for letting me know. I'm going to merge this PR and add some tests in a follow-up PR. 😄

**Review by jcansdale — APPROVED** [review]
Let's get this merged and add some tests in a follow up PR.

**Pull request merged**
